version: "3.9"

services:
  datadog:
    image: datadog/agent:7.54.0
    container_name: datadog
    environment:
      DD_API_KEY: "fake"

      DD_DOGSTATSD_ONLY: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"

      DD_DOGSTATSD_LOG_LEVEL: "debug"

    ports:
      - "18125:8125/udp"
